[build]
  publish = "public"
 
[build.environment]
  NODE_VERSION = "18"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
 
[[redirects]]
  from = "/"
  to = "/solicitud.html"
  status = 200
 
[[redirects]]
  from = "/tu-espacio"
  to = "/index.html"
  status = 200
